name: Blog RSS feed workflow
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog-posts:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.stefankolb.de/feed/feed.xml"
          commit_message: "chore: Update latest blog post list"
